"""Type stubs for Nautilus (nautilus-python) GI module."""

from typing import Any, Optional, Sequence
from gi.repository import GObject, Gio


class FileInfo(GObject.Object):
    """
    Methods actually present on Nautilus 50 (nautilus-python 4.1) FileInfo.
    Note: ``get_size`` was removed — size must come from the local path
    (e.g. ``os.path.getsize``) or from ``get_location()`` + Gio query.
    """
    def get_uri(self) -> str: ...
    def get_activation_uri(self) -> str: ...
    def get_uri_scheme(self) -> str: ...
    def get_mime_type(self) -> str: ...
    def get_name(self) -> str: ...
    def get_location(self) -> Gio.File: ...
    def is_directory(self) -> bool: ...
    def is_gone(self) -> bool: ...


class MenuItem(GObject.Object):
    def __init__(self, *, name: str, label: str, tip: str = ..., icon: str = ...) -> None: ...
    def connect(self, signal: str, callback: Any, *args: Any) -> int: ...
    def set_submenu(self, menu: "Menu") -> None: ...


class Menu(GObject.Object):
    def __init__(self) -> None: ...
    def append_item(self, item: MenuItem) -> None: ...
    def prepend_item(self, item: MenuItem) -> None: ...


class MenuProvider(GObject.GInterface):
    def get_file_items(self, *args: Any) -> list[MenuItem]: ...
    def get_background_items(self, *args: Any) -> list[MenuItem]: ...
